# Generated by Django 4.1.5 on 2023-01-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="name",
            new_name="title",
        ),
    ]
